### ISSUE TITLE
Cannot call external methods with params args

### ISSUE THREAD

**Issue by sapiens** [scriptcs/scriptcs#1066] opened 2015-07-27 00:12 UTC
I have script calling an extension methods from another assembly. 

```csharp
//this throws when invoked from the script
  public static void WriteError(this string data, params object[] args)
        {
            //stuff
        }
```

I've put the definition of `WriteError` into the script and .. it throws there too. I've commented out the whole body, it throws too. Only when I've commented out ` params object[] args` it worked. It appears that it doesn't like the 'param' keyword or something.

However it did work in the past. ScriptCs version I'm using is 0.14.1 on windows.

The error I'm getting

```csharp
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.InitializerDimensions(BoundA
rrayInitialization init)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitAllElementInitializers(A
rrayTypeSymbol arrayType, BoundArrayInitialization inits, Boolean skipConstants)

   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitVectorInitializers(Array
TypeSymbol arrayType, BoundArrayInitialization inits)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArrayCreationExpression(
BoundArrayCreation expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpressi
on expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArgument(BoundExpression
 argument, RefKind refKind)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArguments(ReadOnlyArray`
1 arguments, ReadOnlyArray`1 parameters)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitCallExpression(BoundCall
 call, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpressi
on expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement
 statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitBlockStatement(BoundBloc
k block)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement
 statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitSequencePointWithSpan(Bo
undSequencePointWithSpan node)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement
 statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement
 statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.Generate()
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.Run(MethodSymbol meth, Bound
Statement block, ILBuilder builder, Module module, DiagnosticBag diagnostics, Bo
olean optimize, Boolean emitSequencePoints)
   at Roslyn.Compilers.CSharp.Compiler.GenerateMethodBody(TypeCompilationState c
ompilationState, MethodSymbol method, BoundStatement block, DiagnosticBag diagno
stics, Boolean optimize, Boolean emitSequencePoints, Func`2 mapFileNameToDebugDo
c, ReadOnlyArray`1 namespaceScopes)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileMethod(MethodSymbol meth
odSymbol, ProcessedFieldInitializers& processedInitializers, SynthesizedSubmissi
onFields previousSubmissionFields, TypeCompilationState compilationState)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileNamedType(NamedTypeSymbo
l symbol)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.<>c__DisplayClass6.<VisitNamedT
ype>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.WaitForWorkers()
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileAllMethodBodies(Compilat
ion compilation, Module moduleBeingBuilt, Boolean generateDebugInfo, DiagnosticB
ag diagnostics, CancellationToken cancellationToken)
   at Roslyn.Compilers.CSharp.Compiler.CompileAllMethodBodies(Compilation compil
ation, Module moduleBeingBuilt, Boolean generateDebugInfo, DiagnosticBag diagnos
tics, CancellationToken cancellationToken)
   at Roslyn.Compilers.CSharp.Compilation.Emit(ModuleBuilder moduleBuilder, IAss
emblyLoader assemblyLoader, Func`2 assemblySymbolMapper, CancellationToken cance
llationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyImage)
   at Roslyn.Compilers.CSharp.Compilation.CommonEmit(ModuleBuilder moduleBuilder
, IAssemblyLoader assemblyLoader, Func`2 assemblySymbolMapper, CancellationToken
 cancellationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyIma
ge)
   at Roslyn.Scripting.CommonScriptEngine.TryEmitSubmission(CommonCompilation co
mpilation, DiagnosticBag diagnostics, Type delegateType, Boolean collectible, Ca
ncellationToken cancellationToken, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Compile(String code, String path, Diag
nosticBag diagnostics, Session session, Type delegateType, Type returnType, Canc
ellationToken cancellationToken, Boolean isInteractive, Boolean isExecute, Commo
nCompilation& compilation, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.CompileSubmission[T](String code, Sess
ion session, String path, Boolean isInteractive)
   at ScriptCs.Engine.Roslyn.RoslynScriptEngine.Execute(String code, Session ses
sion)

```

**Comment by sapiens** [comment] 2015-07-27 14:26
I've also noticed it has trouble with array initializers. The code below throws the same exception

```csharp
string[] Bla= new[]{"Something"};
```csharp

**Comment by khellang** [comment] 2015-07-27 14:38
I'm not really sure how this has worked in the past... The exception clearly originates from deep inside the Roslyn scripting bits, and those hasn't been changed - ever. Are you sure that is correct? Do you have a version number where it worked?

**Comment by sapiens** [comment] 2015-07-27 15:11
It worked with version 0.9.0 . Yes, I'm sure it worked. But the weird part is I can invoke a method with variable arguments found in another assembly used by the assembly which contain the methods which don't work :/

**Comment by sapiens** [comment] 2015-07-27 15:37
OK, things are weird. I've cloned the project's old version and it did work. I've downgraded the current versions's scriptcs to the 0.9 version and it still failed. I've upgraded the nugets again to the latest scriptcs version and it works now :| . WTF?! 

So, clearly is not a scriptcs bug. But it still weird, however I might have a clue why this happened. Since Vs 2015 nuget manager doesn't support "update all" , I've used VS 2013 to update the nugets. But after that I've only used VS 2015.  So maybe something got lost. 

When I did the upgrading with VS 2015, each package manually, it worked, so perhaps it was a nuget problem after all.

**Comment by sapiens** [comment] 2015-07-27 16:17
And I'm back to the twilight zone. Running the exe from VS with F5 works. Invoking the exe from cmd line still has the problem. My exe embeds a scriptcs host. Any idea what it might be?

**Comment by djheap** [comment] 2015-07-28 18:31
I have also started experiencing this and believe it started happening on previously working machines in two cases -- it started when I upgraded my dev box to Windows 10, and it started happening when I installed DotNet 4.6 on a Windows 2012 R2 box.

So it seems to be when running on DotNet 4.6 in my experience.

**Comment by adamralph** [comment] 2015-07-28 18:46
.NET 4.6 TCO strikes again?

**Comment by djheap** [comment] 2015-07-28 19:00
Sorry, I'm not familiar with 'TCO' in that context?

**Comment by khellang** [comment] 2015-07-28 19:03
Yeah, I thought about the same yesterday. Can it be a coincidence?

@djheap For reference: http://nickcraver.com/blog/2015/07/27/why-you-should-wait-on-dotnet-46/

**Comment by djheap** [comment] 2015-07-28 19:18
Thanks for the link. In our case the hosting application is 32-bit and so it does not seem to be the culprit, and indeed turning off RyuJIT did not help.

**Comment by djheap** [comment] 2015-07-28 19:23
When searching using the exception call stack, I remember seeing some links mentioning an old Roslyn bug in handling overloaded methods, but I can't find them again. I also saw this: https://github.com/cake-build/cake/issues/241

**Comment by sapiens** [comment] 2015-07-28 19:44
Btw, my app (incidentally a build tool, too) has the problem regardless if it's Debug or Release. AFAIK the .net 4.6 bug strikes only in release mode. It's still strange that it's working properly when launched via VS, as if vshost somehow alleviates the problem.

**Comment by sapiens** [comment] 2015-07-28 19:51
I don't know if it helps but this works (`WriteInfo` is an extension method invoking Console.Writeline)
```csharp
"bla".WriteInfo(new object[0]); //arguments
```
This doesn't
```csharp
"bla {0},{1}".WriteInfo("foo","bar");
```
The workaround is this

```csharp
var list=new List<string>();
list.Add("foo");
list.Add("bar");

"bla {0},{1}".WriteInfo(list.ToArray());

```

This makes me think that the real problem is the initialization of the array. Obviously `new[]{"foo","bar"}` throws too.

**Comment by khellang** [comment] 2015-07-28 20:03
Should we ping someone on the team? @tmat?

**Comment by tmat** [comment] 2015-07-28 20:34
I can't repro using latest Roslyn compilers. This is what I'm trying:

> csc /target:library b.cs
```C#
public static class C
{
  public static void WriteInfo(this string data, params object[] args)
  {
     System.Console.Write(data, args);
  }
}
```

> csc a.csx /r:b.dll
```C#
"bla {0},{1}".WriteInfo("foo","bar");
```

> a.exe
```
bla foo,bar
```

**Comment by sapiens** [comment] 2015-07-28 20:53
I can. `git clone https://github.com/sapiens/MakeSharp.git` . Then open in VS, then build. Write this file "test.cs" to bin\Debug where  makesharp.exe is.

```csharp

[Default]
public class Clean
        {
            public void Run()
            {
                "vvbbb".WriteInfo();
	         var b=new[]{"bla"};
	         b.ForEach(d=>d.ToConsole());	
            }
            
        }
```

Then open cmd and run `makesharp test.cs` . It will throw. 

Next, in VS go to project properties -> debug -> command line arguments and type "test.cs"  . Save then F5 .  It will run without a hitch.

**Comment by khellang** [comment] 2015-07-28 20:56
@sapiens Those are not the latest Roslyn compilers, at least not if you're talking about [the ones in your packages.config](https://github.com/sapiens/MakeSharp/blob/master/src/MakeSharp/packages.config#L12-L13). Those are waaaaay old.

**Comment by sapiens** [comment] 2015-07-28 21:10
I see, then which are the latest ones? The [beta ones](https://www.nuget.org/packages/Microsoft.Framework.Runtime.Roslyn/1.0.0-beta6)?

**Comment by khellang** [comment] 2015-07-28 21:15
Unless @tmat is referring to master-branch-bits, it's https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp etc.

**Comment by djheap** [comment] 2015-07-29 00:48
I can confirm that https://github.com/filipw/scriptcs/tree/feature/roslyn-engines-rc2 fixes the issue for me.

**Comment by khellang** [comment] 2015-07-29 13:26
I'm inclined to mark this as a `roslyn bug` and possibly close it.

We're running on almost 3 year old (alpha) bits here. The fact that we haven't seen more bugs like this surprises me.

Agree?

**Comment by adamralph** [comment] 2015-07-29 13:28
I'm not sure we should close it. We can mark it as a Roslyn bug and close it when we merge https://github.com/scriptcs/scriptcs/pull/1064. It can then be listed as one of the fixes when we push out 0.16.

**Comment by adamralph** [comment] 2015-07-29 13:30
(0.16 or whatever version the Roslyn upgrade goes out in.)

**Comment by filipw** [comment] 2015-09-29 20:56
fixed in https://github.com/scriptcs/scriptcs/pull/1064

**Closed by filipw** 2015-09-29 20:56 UTC
Labels: bug, roslyn bug

**Comment by adamralph** [comment] 2015-09-30 21:37
Has the fix been proven?

**Comment by filipw** [comment] 2015-10-01 09:15
yeah that's why i closed it :wink:
