### ISSUE TITLE
Private static variables cause meaningless exception on mono

### ISSUE THREAD

**Issue by tobiaszuercher** [scriptcs/scriptcs#1073] opened 2015-07-31 11:12 UTC
The following script: 

``` csharp
using Octopus.Client;

private static string regexString = @"[\d\.]+[^-]+\.(?<number>\d+)-{0}";
private static string regexStringWithoutBranch = @"[\d\.]+[^-]+\.(?<number>\d+)$";

var octopusUrl = "https://demo.octopusdeploy.com";
var octopusApi = "api-key";

System.Net.ServicePointManager.ServerCertificateValidationCallback = (sender, cert, chain, error) => true;

var endpoint = new OctopusServerEndpoint(octopusUrl, octopusApi);
var repository = new OctopusRepository(endpoint);

var releases = repository.Releases.FindAll().ToList();

foreach (var release in releases)
{
    Console.WriteLine(release.Version);
}
```

The scripts needs `scriptcs -install Octopus.Client`
Works perfectly on windows. On ubuntu with mono, i get the following error:

```
tobi@tobuntu-v:~/Desktop/scriptcs$ scriptcs issue.csx 
ERROR: Script execution failed: Argument is out of range.
Parameter name: index.
```

How can i get more info about the error? The -debug flag doesn't give me enough information to fix the issue.

Is it possible that this is a mono issue?

**Comment by adamralph** [comment] 2015-07-31 12:08
@tobiaszuercher it may well be a mono issue.

In the forthcoming 0.15 release (hopefully just days away) the full stack trace will be printed to the console when an error occurs (see https://github.com/scriptcs/scriptcs/issues/987).

In the meantime, you could try running your script using the nightly build  https://www.myget.org/gallery/scriptcsnightly

**Comment by ztone** [comment] 2015-07-31 17:39
Hi @tobiaszuercher.  

This is a quirk, a small difference between the mono and the roslyn engine.  Mono doesn't like their toplevel variables to have access modifiers nor being static  ... probably because they make little sense in this context.

So this should work in mono
```c#
string regexString = @"[\d\.]+[^-]+\.(?<number>\d+)-{0}";
string regexStringWithoutBranch = @"[\d\.]+[^-]+\.(?<number>\d+)$";
```

We will probably not fix this as this is a mono issue, not scriptcs.
Hope this helps!

FYI @adamralph 

p.s yeah, the error message you got sucked ... we're working on it

**Comment by adamralph** [comment] 2015-08-01 10:55
@ztone thanks for the info! I think even with the stack trace we would have had a hard time figuring that out :smile: 

btw
> We will probably not fix this as this is a mono issue, not scriptcs.

I guess you mean

> We will probably ~~not~~ fix this as this is a mono issue, not scriptcs.

**Comment by ztone** [comment] 2015-08-01 14:08
Hi @adamralph 

What I meant is that this "bug" (if it is a bug, might be by design) is in Mono.CSharp and therefore not maintained by us.  Even if I would issue a PR to the mono project hat fixes this I'm not sure that it will be accepted because why does a toplevel variable need to be private?

However what we might be able to do here, just to make our roslyn and mono engine a bit more compatible, is to use our pre-parser and remove any keywords from toplevel variables before passing it to the Mono.CSharp evaluator.

**Comment by adamralph** [comment] 2015-08-02 00:16
@ztone ok, makes sense.

The whole top-level variable thing is weird. In Roslyn, these actually end up (counter-intuitively) as being fields in a class. I design I've challenged, but it seems to be sticking. I guess we could do what you suggest and strip away the access and static modifiers in pre-parsing.

**Comment by tobiaszuercher** [comment] 2015-08-03 08:28
wow, thank you all for the comments!

i just copied & pasted code from a console exe. and yes, the private static doesn't really make sense there! still happy to see more output if something goes wrong (even in that case a stacktrace wouldn't be that helpful).

looking forward to 0.15! thank you guys <3

**Comment by filipw** [comment] 2017-04-06 12:12
fixed by https://github.com/scriptcs/scriptcs/pull/1216

**Closed** 2017-04-06 12:41 UTC
Labels: bug, mono, taken

**Comment by tobiaszuercher** [comment] 2017-04-06 14:00
thank you guys for all your effort!
