### ISSUE TITLE
Cannot Upgrade in Chocolatey

### ISSUE THREAD

**Issue by mbaker-dev** [scriptcs/scriptcs#1094] opened 2015-09-15 17:29 UTC
I'm currently on v0.14.1 on my Windows 7 PC, but I've been having this issue for a while. When trying to upgrade via Chocolatey I get the following output:

>You have scriptcs v0.14.1 installed. Version 0.15.0 is available based on your source(s).
>scriptcs not upgraded. An error occurred during installation:
> Already referencing a newer version of 'NuGet.CommandLine'.
>The upgrade of scriptcs was NOT successful.
>scriptcs not upgraded. An error occurred during installation:
> Already referencing a newer version of 'NuGet.CommandLine'.
> Unsuccessful operation for scriptcs.
>  Do you want to rollback to previous version (package files only)?
> 1) yes
> 2) no

The only way I am able to upgrade is to `choco uninstall scriptcs` and then `choco install scriptcs`.

**Comment by adamralph** [comment] 2015-09-15 18:07
Hi @mbaker-dev, thanks for reporting this, it's been reported before and unfortunately it's a Chocolatey problem which we cannot fix in scriptcs. See https://github.com/chocolatey/choco/issues/227

Closing as a duplicate of https://github.com/scriptcs/scriptcs/issues/1015

**Closed by adamralph** 2015-09-15 18:07 UTC
Labels: duplicate
