### ISSUE TITLE
Engine paths hardcoded

### ISSUE THREAD

**Issue by awb99** [scriptcs/scriptcs#1158] opened 2016-04-22 07:50 UTC
I moved all dlls other than scriptcs to a different directory and use the following app.config:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5" />
  </startup>

  <runtime>

<!-- otherwise scriptcs cannot be executed on network drive -->
<loadFromRemoteSources enabled="true"/>

    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
           <probing privatePath="scriptcs;manyOtherLibraries" />
    </assemblyBinding>

</runtime>

</configuration>

```

it only would work when I moved the engine dlls to the same directory as scriptcs.exe.

I believe this is a bug.

**Comment by awb99** [comment] 2016-04-22 07:51
In case you guys believe that I am crazy to do that: I have 200 (private) dlls that I want to use with scriptcs that are nicely organized in folders. And the scriptcs libraries should also go into one folder.

**Comment by filipw** [comment] 2016-04-22 07:58
it is not a bug, it was intentional. 

The scripting engines are not loaded using regular assembly references, but instead loaded manually into the app domain. Then the engine modules are discovered in a lazy way using MEF, or in a fast path with reflection, from the host bin folder (which is `scriptcs.exe` or any custom location in case you are embedding scriptcs in your own process).

This has several design and performance benefits; the scenario you mention never came up before.

**Comment by awb99** [comment] 2016-04-22 14:35
I understand that. And this is a good idea. I  agree. However, the engine dll could be loaded from any path that is a valid probing path. If you limit yourself to only the path of the executeable, then this is not enough. IMHO.

**Comment by glennblock** [comment] 2017-01-03 04:59
Closing as By Design

**Closed by glennblock** 2017-01-03 04:59 UTC
